# Generated by Django 4.2.16 on 2024-12-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', models.CharField(max_length=255, unique=True)),
                ('customer', models.CharField(max_length=255)),
                ('bay_no', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('Yard', 'Yard')], default='Yard', max_length=5)),
                ('wo_status', models.CharField(choices=[('WOAPPR', 'WOAPPR'), ('Approved', 'Approved'), ('Inspection', 'Inspection'), ('In Progress', 'In Progress'), ('Parts ordered', 'Parts ordered'), ('Declined', 'Declined'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
